const types = {
  CREATECOMPTEEMPLOYEE: 'CREATECOMPTEEMPLOYEE',
  AUTH: 'AUTH',
  CHECKAUTH: 'CHECKAUTH',
  LOGOUT: 'LOGOUT',
  DEPARTEMENT: 'DEPARTEMENT',
  GETALLDEPARTEMENTS: 'GETALLDEPARTEMENTS',
  GETALLTICHNICIENS: 'GETALLTICHNICIENS',
  CREATETICKET: 'CREATETICKET',
  GETALLTICKES: 'GETALLTICKES',
  ASSIGNTICKET: 'ASSIGNTICKET',
  GETTICKENASSIGNTICH: 'GETTICKENASSIGNTICH',
  REASSIGNEDORRESERVED: 'REASSIGNEDORRESERVED',
  HISTORYTICKET: 'HISTORYTICKET',
  AUTH_ERROR: 'AUTH_ERROR',
  TOGGLE_SUCCESS: 'TOGGLE_SUCCESS',
};

export default types;
